server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: itknowledgebase
  ai:
    mcp:
      server:
        protocol: STREAMABLE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/auth/realms/document-chat}
          audiences:
            - mcp-api

itknowledgebase:
  dir:
    path: ${ITKNOWLEDGEBASE_DIR_PATH:data}
